version: 0.0
os: linux
files:
  - source: wati-webhook/
    destination: /home/ubuntu/wati-webhook
hooks:
  ApplicationStop:
    - location: /home/ubuntu/wati-webhook/scripts/scripts/application_stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: /home/ubuntu/wati-webhook/scripts/scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: /home/ubuntu/wati-webhook/scripts/scripts/application_start.sh
      timeout: 300
      runas: ubuntu